osx_image: xcode9.4
language: swift
branches:
  only:
      - develop
  except:
      - screenshot
env:
  global:
  - PROJECT="Example/RxValidatorExample/RxValidatorExample.xcworkspace"
  - SCHEME="RxValidatorExampleTests"
  - podfile="Example/RxValidatorExample/Podfile"
  matrix:
  - TEST=1 DESTINATION="platform=iOS Simulator,name=iPhone 8,OS=11.3"
  - TEST=1 DESTINATION="arch=x86_64"
  - TEST=1 DESTINATION="OS=11.3,name=Apple TV"
  - TEST=0 DESTINATION="OS=4.3,name=Apple Watch - 38mm"

before_install:
  - gem install cocoapods
  - pod --version

install: true
  
script:
  - pod repo update && pod update
  - set -o pipefail
  - xcodebuild clean build test
      -workspace "$PROJECT"
      -scheme "$SCHEME"
      -sdk "$SDK"
      -destination "$DESTINATION"
      -configuration Debug
      - travis_wait 30 pod lib lint RxValidator.podspec
      -enableCodeCoverage YES
      CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c