osx_image: xcode9.4
language: swift
cache: cocoapods
branches:
  only:
      - develop
  except:
      - screenshot
env:
  global:
  - PROJECT="Example/RxValidatorExample/RxValidatorExample.xcworkspace"
  - SCHEME="RxValidatorExample"
  matrix:
  - TEST=1 DESTINATION="platform=iOS Simulator,name=iPhone 8,OS=11.3"
  # - TEST=1 DESTINATION="arch=x86_64"
  # - TEST=1 DESTINATION="OS=11.3,name=Apple TV"
  # - TEST=0 DESTINATION="OS=4.3,name=Apple Watch - 38mm"

before_install:
  - set -o pipefail
  - brew update
  - gem install cocoapods
  - pod --version

install: 
  - swift --version
  
script:
  - pod repo update && pod update --project-directory=Example/RxValidatorExample/
  - xcodebuild test
      -workspace "$PROJECT"
      -scheme "$SCHEME"
      -sdk "$SDK"
      -destination "$DESTINATION"
      -configuration Debug
      -enableCodeCoverage YES
      CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
  - travis_wait 30 pod lib lint RxValidator.podspec
