# os: osx
osx_image: xcode9.4
language: swift
sudo: required
xcode_scheme: RxValidatorExample
xcode_workspace: Example/RxValidatorExample/RxValidatorExample.xcworkspace
podfile: Example/RxValidatorExample/Podfile
cache: cocoapods

branches:
  only:
      - develop
  except:
      - screenshot
# env:
#   global:
#   - PROJECT="RxValidatorExample.xcworkspace"
#   - SCHEME="RxValidatorExample"
#   matrix:
#   - TEST=1 DESTINATION="platform=iOS Simulator,name=iPhone X,OS=11.3"
  # - TEST=1 DESTINATION="arch=x86_64"
  # - TEST=1 DESTINATION="OS=11.4,name=Apple TV"
  # - TEST=0 DESTINATION="OS=4.3,name=Apple Watch - 38mm"

before_install:
  - set -o pipefail
  
  

install: 
  - swift --version
  # - bundle install
  - gem install cocoapods
  - pod --version

before_script:
  - pod repo update
  - pod update --project-directory=Example/RxValidatorExample
  
script:
  # - pod lib lint RxValidator.podspec
  # - cd Example/RxValidatorExample/
  # - pod repo update
  - travis_wait 30 pod lib lint --verbose --allow-warnings --fail-fast
  # - pod update
  # - xcodebuild clean build test
  #     -workspace "$PROJECT"
  #     -scheme "$SCHEME"
  #     -destination "$DESTINATION"
  #     CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c --test --color
  
